CREATE DATABASE IF NOT EXISTS tododatabase;
USE tododatabase;
CREATE TABLE IF NOT EXISTS tasktable (Id INT AUTO_INCREMENT primary key NOT NULL, task TEXT);
CREATE TABLE IF NOT EXISTS donetasks (Id INT AUTO_INCREMENT primary key NOT NULL, task TEXT);